sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=myrobot
    # REGISTRY_PASS=...
    - secret: "<something long>"

before_script:
  - docker pull teploff/name || true

script:
  - docker build --pull --cache-from teploff/name --tag teploff/name .
  - docker run teploff/name

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push teploff/name
  on:
    branch: master
